sudo: false
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
env:
  - DEBUG=1
python:
  - "3.5"
  - "3.6"
install:
  - pip install -U pip
  - pip install -r requirements/local.txt
script:
  - py.test -ra -vvv --doctest-modules --cov
